theme: minima
title: My first github page with jekyII
author: chzheng0
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Same as the title.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
